# Generated by Django 5.0.4 on 2024-04-17 03:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
