# Generated by Django 5.0.4 on 2024-04-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='province',
            field=models.CharField(choices=[('all', 'All'), ('one', 'One'), ('second', 'Second'), ('third', 'Third'), ('forth', 'Forth'), ('fifth', 'Fifth'), ('six', 'Six'), ('SEVEN', 'Seven')], default='all', max_length=100),
        ),
    ]
