# Generated by Django 5.0.4 on 2024-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
