# Generated by Django 5.0.4 on 2024-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
